Revert "interfaces: try to sync dhclient-script #2542"
PR: https://github.com/opnsense/core/issues/3197

diff --git a/src/opnsense/scripts/interfaces/dhclient-script b/src/opnsense/scripts/interfaces/dhclient-script
--- a/src/opnsense/scripts/interfaces/dhclient-script
+++ b/src/opnsense/scripts/interfaces/dhclient-script
@@ -1,5 +1,5 @@
 #!/bin/sh
-#
+# $Id$
 # $OpenBSD: dhclient-script,v 1.6 2004/05/06 18:22:41 claudio Exp $
 # $FreeBSD: src/sbin/dhclient/dhclient-script,v 1.4 2005/06/10 03:41:18 brooks Exp $
 #
@@ -17,18 +17,24 @@
 # ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
 # OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
 #
-#
 
-ARP=/usr/sbin/arp
+NETSTAT=/usr/bin/netstat
+GREP=/usr/bin/grep
+AWK=/usr/bin/awk
 HOSTNAME=/bin/hostname
-IFCONFIG='/sbin/ifconfig -n'
+GREP=/usr/bin/grep
+ROUTE=/sbin/route
+SED=/usr/bin/sed
+ARP=/usr/sbin/arp
+IFCONFIG=/sbin/ifconfig
+PFCTL=/sbin/pfctl
 
 LOCALHOST=127.0.0.1
 
 if [ -x /usr/bin/logger ]; then
 	LOGGER="/usr/bin/logger -s -p user.notice -t dhclient"
 else
-	LOGGER=echo
+	LOGGER="echo"
 fi
 
 #
@@ -37,20 +43,18 @@ fi
 
 check_hostname() {
 	current_hostname=`$HOSTNAME`
-	if [ -z "$current_hostname" ]; then
-		$LOGGER "New Hostname ($interface): $new_host_name"
-		$HOSTNAME $new_host_name
-	elif [ "$current_hostname" = "$old_host_name" -a \
-	       "$new_host_name" != "$old_host_name" ]; then
+	if [ -z "$current_hostname" ] || \
+	   [ "$current_hostname" = "$old_host_name" -a \
+	     "$new_hostname" != "$old_host_name" ]; then
 		$LOGGER "New Hostname ($interface): $new_host_name"
 		$HOSTNAME $new_host_name
 	fi
 }
 
 arp_flush() {
-	arp -an -i $interface | \
-		sed -n -e 's/^.*(\(.*\)) at .*$/arp -d \1/p' | \
-		sh >/dev/null 2>&1
+	$ARP -an -i $interface | \
+		$SED -n -e 's/^.*(\(.*\)) at .*$/arp -d \1/p' | \
+		/bin/sh >/dev/null 2>&1
 }
 
 delete_old_states() {
@@ -62,8 +66,8 @@ delete_old_states() {
 		$LOGGER "Comparing IPs: Old: ${OLD_IP} New: ${new_ip_address}"
 		if [ -n "${OLD_IP}" ] && [ "${OLD_IP}" != "${new_ip_address}" ]; then
 			$LOGGER "Removing states from old IP '${OLD_IP}' (new IP '${new_ip_address}')"
-			pfctl -i $interface -Fs
-			pfctl -K ${OLD_IP}/32
+			${PFCTL} -i $interface -Fs
+			${PFCTL} -K ${OLD_IP}/32
 			_FLUSHED=1
 		fi
 	fi
@@ -78,30 +82,35 @@ delete_old_states() {
 		$LOGGER "Comparing Routers: Old: ${OLD_ROUTER} New: ${new_routers}"
 		if [ "${OLD_ROUTER}" != "${new_routers}" ]; then
 			$LOGGER "Removing states through old gateway '${OLD_ROUTER}' (new gateway '${new_routers}')"
-			pfctl -i $interface -Fs
+			${PFCTL} -i $interface -Fs
 		fi
 	fi
 }
 
 delete_old_address() {
-	rm -f /var/db/${interface}_ip
-	eval "$IFCONFIG $interface inet -alias $old_ip_address $medium"
+	/bin/rm -f /var/db/${interface}_ip
+	$IFCONFIG $interface inet -alias $old_ip_address $medium
 }
 
 add_new_address() {
-	eval "$IFCONFIG $interface \
+
+	$LOGGER "Starting add_new_address()"
+
+	$LOGGER "ifconfig $interface inet $new_ip_address netmask $new_subnet_mask broadcast $new_broadcast_address $medium"
+
+	$IFCONFIG $interface \
 		inet $new_ip_address \
 		netmask $new_subnet_mask \
 		broadcast $new_broadcast_address \
-		$medium"
+		$medium
 
 	$LOGGER "New IP Address ($interface): $new_ip_address"
 	$LOGGER "New Subnet Mask ($interface): $new_subnet_mask"
 	$LOGGER "New Broadcast Address ($interface): $new_broadcast_address"
 	$LOGGER "New Routers ($interface): $new_routers"
 
-	# This is necessary otherwise dpinger will try to ping all 1s address
-        # XXX still true?!
+
+	# This is necessary otherwise apinger will try to ping all 1s address
 	if [ -n "$new_routers" ] && [ "$new_routers" != "255.255.255.255" ]; then
 		echo $new_routers > /tmp/${interface}_router
 	fi
@@ -111,7 +120,7 @@ add_new_address() {
 delete_old_alias() {
 	if [ -n "$alias_ip_address" ]; then
 		$IFCONFIG $interface inet -alias $alias_ip_address > /dev/null 2>&1
-		#route delete $alias_ip_address $LOCALHOST > /dev/null 2>&1
+		$ROUTE delete $alias_ip_address $LOCALHOST > /dev/null 2>&1
 	fi
 }
 
@@ -119,7 +128,7 @@ add_new_alias() {
 	if [ -n "$alias_ip_address" ]; then
 		$IFCONFIG $interface inet alias $alias_ip_address netmask \
 		    $alias_subnet_mask
-		#route add $alias_ip_address $LOCALHOST
+		$ROUTE add $alias_ip_address $LOCALHOST
 	fi
 }
 
@@ -149,7 +158,8 @@ fill_classless_routes() {
 }
 
 delete_old_routes() {
-	#route delete "$old_ip_address" $LOCALHOST >/dev/null 2>&1
+	$LOGGER "Deleting old routes"
+
 	if [ -n "$old_classless_routes" ]; then
 		fill_classless_routes "$old_classless_routes"
 		set $classless_routes
@@ -160,20 +170,20 @@ delete_old_routes() {
 		return 0;
 	fi
 
-	# If we supported multiple default routes, we'd be removing each
-	# one here.  We don't so just delete the default route if it's
-	# through our interface.
-	if is_default_interface; then
-		route delete default >/dev/null 2>&1
-		rm -f /tmp/${interface}_router
+	# Only allow the default route to be overridden if it's on our own interface
+	if [ -f "/tmp/${interface}_defaultgw" ]; then
+		for router in $old_routers; do
+			$ROUTE delete default $router >/dev/null 2>&1
+			/bin/rm -f /tmp/${interface}_router
+		done
 	fi
 
 	if [ -n "$old_static_routes" ]; then
 		set $old_static_routes
 		while [ $# -gt 1 ]; do
-			route delete "$1" "$2"
+			$ROUTE delete "$1" "$2"
 			shift; shift
-			rm -f /tmp/${interface}_router
+                        /bin/rm -f /tmp/${interface}_router
 		done
 	fi
 
@@ -181,7 +191,7 @@ delete_old_routes() {
 }
 
 add_new_routes() {
-	#route add $new_ip_address $LOCALHOST >/dev/null 2>&1
+	$LOGGER "Adding new routes to interface: $interface"
 
 	# RFC 3442: If the DHCP server returns both a Classless Static
 	# Routes option and a Router option, the DHCP client MUST ignore
@@ -191,7 +201,6 @@ add_new_routes() {
 	# MUST NOT install the routes specified in the Static Routes
 	# option (option code 33) if both a Static Routes option and the
 	# Classless Static Routes option are provided.
-
 	if [ -n "$new_classless_routes" ]; then
 		fill_classless_routes "$new_classless_routes"
 		$LOGGER "New Classless Static Routes ($interface): $classless_routes"
@@ -211,18 +220,18 @@ add_new_routes() {
 	EXISTSGW=`/bin/ls -l /tmp/*_defaultgw | /usr/bin/wc -l`
 	# Only allow the default route to be overridden if it's on our own interface
 	if [ -f "/tmp/${interface}_defaultgw" -o $EXISTSGW -eq 0 ]; then
-		route delete default
+		$ROUTE delete default
 		for router in $new_routers; do
 			if [ "$new_ip_address" = "$router" -o "$router" = "255.255.255.255" ]; then
-				route add default -iface $interface
-				echo route add default -iface $interface | $LOGGER
+				$ROUTE add default -iface $interface
+				echo $ROUTE add default -iface $interface | $LOGGER
 				# NOTE: Do not activate this for all ones address since pf(4) will try to forward packets to it.
 				if [ "$new_ip_address" = "$router" ]; then
 					echo $router > /tmp/${interface}_router
 				fi
 			else
-				route add default $router
-				echo route add default $router | $LOGGER
+				$ROUTE add default $router
+				echo $ROUTE add default $router | $LOGGER
 				echo $router > /tmp/${interface}_router
 			fi
 			ADDED_ROUTE=yes
@@ -236,7 +245,7 @@ add_new_routes() {
 		$LOGGER "New Static Routes ($interface): $new_static_routes"
 		set $new_static_routes
 		while [ $# -gt 1 ]; do
-			route add $1 $2
+			$ROUTE add $1 $2
 			if [ "$ADDED_ROUTE" = "no" ]; then
 				echo $2 > /tmp/${interface}_router
 			fi
@@ -250,19 +259,19 @@ add_new_resolv_conf() {
 	if [ -f "/var/etc/nameserver_$interface" ]; then
 		# Remove old entries
 		for nameserver in `cat /var/etc/nameserver_$interface`; do
-			route delete $nameserver >/dev/null 2>&1
+			$ROUTE delete $nameserver >/dev/null 2>&1
 		done
 	fi
 	if [ -n "$new_domain_name_servers" ]; then
-		rm -f /var/etc/nameserver_$interface
-		ALLOWOVERRIDE=$(grep -c dnsallowoverride /conf/config.xml)
+		/bin/rm -f /var/etc/nameserver_$interface
+		ALLOWOVERRIDE=`/usr/bin/grep dnsallowoverride /conf/config.xml | /usr/bin/wc -l`
 		for nameserver in $new_domain_name_servers; do
 			# Add a route to the nameserver out the correct interface
 			# so that mulitple wans work correctly with multiple dns
 			# also backup the nameserver for later route removal
 			if [ $ALLOWOVERRIDE -gt 0 ]; then
 				echo $nameserver >>/var/etc/nameserver_$interface
-				route add $nameserver -iface $interface
+				$ROUTE add $nameserver -iface $interface
 			fi
 		done
 		echo $new_domain_name >/var/etc/searchdomain_$interface
@@ -271,39 +280,9 @@ add_new_resolv_conf() {
 	return 0
 }
 
-# Must be used on exit.   Invokes the local dhcp client exit hooks, if any.
-exit_with_hooks() {
-	exit_status=$1
-	if [ -f /etc/dhclient-exit-hooks ]; then
-		. /etc/dhclient-exit-hooks
-	fi
-	# probably should do something with exit status of the local script
-	exit $exit_status
-}
-
-# Get the interface with the current ipv4 default route on it using only
-# commands that are available prior to /usr being mounted.
-is_default_interface()
-{
-	routeget="`route -n get -inet default`"
-	oldifs="$IFS"
-	IFS="
-"
-	defif=
-	for line in $routeget ; do
-		case $line in
-		*interface:*)
-			defif=${line##*: }
-			;;
-		esac
-	done
-	IFS=${oldifs}
-
-	if [ -z "$defif" -o "$defif" = "$interface" ]; then
-		return 0
-	else
-		return 1
-	fi
+# Notify rc.newwanip of changes to an interface
+notify_rc_newwanip() {
+	/usr/local/etc/rc.newwanip $interface
 }
 
 #
@@ -312,6 +291,7 @@ is_default_interface()
 
 # Invoke the local dhcp client enter hooks, if they exist.
 if [ -f /etc/dhclient-enter-hooks ]; then
+	$LOGGER "dhclient-enter-hooks"
 	exit_status=0
 	. /etc/dhclient-enter-hooks
 	# allow the local script to abort processing of this state
@@ -321,20 +301,26 @@ if [ -f /etc/dhclient-enter-hooks ]; then
 	fi
 fi
 
-: ${resolvconf_enable="NO"}
+#if [ -x $ROUTE ]; then
+#	if_defaultroute=`$ROUTE -n get -inet default | $GREP interface | $AWK '{print $2}'`
+#else
+#	$LOGGER "if_defaultroute"
+#	if_defaultroute="x"
+#fi
 
+$LOGGER $reason
 case $reason in
 MEDIUM)
-	eval "$IFCONFIG $interface $medium"
-	eval "$IFCONFIG $interface inet -alias 0.0.0.0 $medium" >/dev/null 2>&1
-	sleep 1
+	$IFCONFIG $interface $medium
+	$IFCONFIG $interface inet -alias 0.0.0.0 $medium >/dev/null 2>&1
+	/bin/sleep 1
 	;;
 
 PREINIT)
 	delete_old_alias
-	$IFCONFIG $interface inet alias 0.0.0.0 netmask 255.0.0.0 broadcast 255.255.255.255 up
+	$IFCONFIG $interface inet 0.0.0.0 netmask 0.0.0.0 broadcast 255.255.255.255 up
 	delete_old_states
-	rm -f /tmp/${interface}_router
+	/bin/rm -f /tmp/${interface}_router
 	;;
 
 ARPCHECK|ARPSEND)
@@ -347,7 +333,8 @@ BOUND|RENEW|REBIND|REBOOT)
 		delete_old_states
 	fi
 	if [ -n "$old_ip_address" ]; then
-		if [ "$old_ip_address" != "$alias_ip_address" ]; then
+		if [ -n "$alias_ip_address" ] && \
+		   [ "$old_ip_address" != "$alias_ip_address" ]; then
 			delete_old_alias
 			changes="yes"
 		fi
@@ -365,15 +352,14 @@ BOUND|RENEW|REBIND|REBOOT)
 		add_new_routes
 		changes="yes"
 	fi
-	if [ "$new_ip_address" != "$alias_ip_address" ]; then
+	if [ -n "$alias_ip_address" ] && \
+       [ "$new_ip_address" != "$alias_ip_address" ]; then
 		add_new_alias
 		changes="yes"
 	fi
-	if is_default_interface; then
-		add_new_resolv_conf
-	fi
+	add_new_resolv_conf
 	if [ "$changes" = "yes" ] ; then
-		/usr/local/etc/rc.newwanip $interface
+		notify_rc_newwanip
 	fi
 	;;
 
@@ -384,53 +370,37 @@ EXPIRE|FAIL)
 		delete_old_address
 		delete_old_routes
 	fi
-	if [ -x $ARP ]; then
-		$ARP -d -a -i $interface
-	fi
-	# XXX Why add alias we just deleted above?
-	add_new_alias
-	if is_default_interface; then
-		case $resolvconf_enable in
-		# "no", "false", "off", or "0"
-		[Nn][Oo]|[Ff][Aa][Ll][Ss][Ee]|[Oo][Ff][Ff]|0)
-			if [ -f /etc/resolv.conf.save ]; then
-				cat /etc/resolv.conf.save > /etc/resolv.conf
-			fi
-			;;
-		*)
-			/sbin/resolvconf -d ${interface}
-			;;
-		esac
-	fi
 	;;
 
 TIMEOUT)
 	delete_old_alias
 	add_new_address
-	sleep 1
+	/bin/sleep 1
 	if [ -n "$new_routers" ]; then
 		$LOGGER "New Routers ($interface): $new_routers"
 		set "$new_routers"
-		if ping -q -c 1 -t 1 "$1"; then
+		if /sbin/ping -q -c 1 -t 1 "$1"; then
 			if [ "$new_ip_address" != "$alias_ip_address" ]; then
 				add_new_alias
 			fi
 			add_new_routes
-			if ! is_default_interface; then
-				/usr/local/etc/rc.newwanip $interface
-				exit_with_hooks 0
-			fi
 			if add_new_resolv_conf; then
-				/usr/local/etc/rc.newwanip $interface
-				exit_with_hooks 0
+				notify_rc_newwanip
 			fi
 		fi
 	fi
-	eval "$IFCONFIG $interface inet -alias $new_ip_address $medium"
+	$IFCONFIG $interface inet -alias $new_ip_address $medium
 	delete_old_states
 	delete_old_routes
-	exit_with_hooks 1
 	;;
 esac
 
-exit_with_hooks 0
+# Invoke the local dhcp client exit hooks, if they exist.
+if [ -f /etc/dhclient-exit-hooks ]; then
+	$LOGGER "dhclient-exit-hooks"
+	exit_status=0
+	. /etc/dhclient-exit-hooks
+	# allow the local script to abort processing of this state
+	# local script must set exit_status variable to nonzero.
+	exit $exit_status
+fi
